# Site settings
title: S.j. Sakib
description: 'Yet another Sapiens'
url: 'http://sjsakib.github.io'
baseurl: ''
TZ: Asia/Dhaka
future: yes
google_analytics: 'UA-90813960-2'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'S.j. Sakib'
  email: sjsakib.bd@gmail.com
  twitter_username: sjsakib
  facebook_username: sjsakib
  github_username:  sjsakib
  # linkedin_username:  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jemoji
  - jekyll-paginate

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
